# -*- coding: utf-8 -*-
"""To do list.pynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a3x2BSWFlYRS4AfmxTk9IgL7p1BZGX4c
"""

tasks = []

def show_tasks():
    if not tasks:
        print("No tasks in the To-Do list.")
    else:
        print("Tasks in the To-Do list:")
        for i, task in enumerate(tasks, 1):
            print(f"{i}. {task}")

def add_task(task):
    tasks.append(task)
    print(f"Task '{task}' added to the To-Do list.")

def delete_task(task_index):
    if 1 <= task_index <= len(tasks):
        deleted_task = tasks.pop(task_index - 1)
        print(f"Task '{deleted_task}' deleted from the To-Do list.")
    else:
        print("Invalid task index.")

def main():
    while True:
        print("\n1. Show Tasks\n2. Add Task\n3. Delete Task\n4. Exit")
        choice = input("Enter your choice: ")

        if choice == "1":
            show_tasks()
        elif choice == "2":
            task = input("Enter task to add: ")
            add_task(task)
        elif choice == "3":
            show_tasks()
            task_index = int(input("Enter the task number to delete: "))
            delete_task(task_index)
        elif choice == "4":
            print("Exiting the To-Do List application.")
            break
        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    main()